version "3.8"

services:
    web:
        image: httpd:latest
        container_name: apache_html
        ports:
            - "8080:80"
        volumes:
            - ./html:/usr/local/apache2/htdocs/